// Code generated by protoc-gen-go. DO NOT EDIT.
// source: car_sharing.proto

package CarSharing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// request
type RegisterCarRequest struct {
	OwnerName            string   `protobuf:"bytes,1,opt,name=OwnerName,proto3" json:"OwnerName,omitempty"`
	CarModel             string   `protobuf:"bytes,2,opt,name=CarModel,proto3" json:"CarModel,omitempty"`
	Place                string   `protobuf:"bytes,3,opt,name=Place,proto3" json:"Place,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCarRequest) Reset()         { *m = RegisterCarRequest{} }
func (m *RegisterCarRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterCarRequest) ProtoMessage()    {}
func (*RegisterCarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_sharing_ee7a01c7a2a6d540, []int{0}
}
func (m *RegisterCarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCarRequest.Unmarshal(m, b)
}
func (m *RegisterCarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCarRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterCarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCarRequest.Merge(dst, src)
}
func (m *RegisterCarRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterCarRequest.Size(m)
}
func (m *RegisterCarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCarRequest proto.InternalMessageInfo

func (m *RegisterCarRequest) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *RegisterCarRequest) GetCarModel() string {
	if m != nil {
		return m.CarModel
	}
	return ""
}

func (m *RegisterCarRequest) GetPlace() string {
	if m != nil {
		return m.Place
	}
	return ""
}

func (m *RegisterCarRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *RegisterCarRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

// response
type RegisterCarReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	CarId                string   `protobuf:"bytes,2,opt,name=CarId,proto3" json:"CarId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCarReply) Reset()         { *m = RegisterCarReply{} }
func (m *RegisterCarReply) String() string { return proto.CompactTextString(m) }
func (*RegisterCarReply) ProtoMessage()    {}
func (*RegisterCarReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_sharing_ee7a01c7a2a6d540, []int{1}
}
func (m *RegisterCarReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCarReply.Unmarshal(m, b)
}
func (m *RegisterCarReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCarReply.Marshal(b, m, deterministic)
}
func (dst *RegisterCarReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCarReply.Merge(dst, src)
}
func (m *RegisterCarReply) XXX_Size() int {
	return xxx_messageInfo_RegisterCarReply.Size(m)
}
func (m *RegisterCarReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCarReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCarReply proto.InternalMessageInfo

func (m *RegisterCarReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RegisterCarReply) GetCarId() string {
	if m != nil {
		return m.CarId
	}
	return ""
}

// request
type SearchCarsRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	CarModel             string   `protobuf:"bytes,2,opt,name=CarModel,proto3" json:"CarModel,omitempty"`
	Place                string   `protobuf:"bytes,3,opt,name=Place,proto3" json:"Place,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchCarsRequest) Reset()         { *m = SearchCarsRequest{} }
func (m *SearchCarsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchCarsRequest) ProtoMessage()    {}
func (*SearchCarsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_sharing_ee7a01c7a2a6d540, []int{2}
}
func (m *SearchCarsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchCarsRequest.Unmarshal(m, b)
}
func (m *SearchCarsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchCarsRequest.Marshal(b, m, deterministic)
}
func (dst *SearchCarsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchCarsRequest.Merge(dst, src)
}
func (m *SearchCarsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchCarsRequest.Size(m)
}
func (m *SearchCarsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchCarsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchCarsRequest proto.InternalMessageInfo

func (m *SearchCarsRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SearchCarsRequest) GetCarModel() string {
	if m != nil {
		return m.CarModel
	}
	return ""
}

func (m *SearchCarsRequest) GetPlace() string {
	if m != nil {
		return m.Place
	}
	return ""
}

func (m *SearchCarsRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *SearchCarsRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

// response
type SearchCarsReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	CarId                string   `protobuf:"bytes,2,opt,name=CarId,proto3" json:"CarId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchCarsReply) Reset()         { *m = SearchCarsReply{} }
func (m *SearchCarsReply) String() string { return proto.CompactTextString(m) }
func (*SearchCarsReply) ProtoMessage()    {}
func (*SearchCarsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_sharing_ee7a01c7a2a6d540, []int{3}
}
func (m *SearchCarsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchCarsReply.Unmarshal(m, b)
}
func (m *SearchCarsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchCarsReply.Marshal(b, m, deterministic)
}
func (dst *SearchCarsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchCarsReply.Merge(dst, src)
}
func (m *SearchCarsReply) XXX_Size() int {
	return xxx_messageInfo_SearchCarsReply.Size(m)
}
func (m *SearchCarsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchCarsReply.DiscardUnknown(m)
}

var xxx_messageInfo_SearchCarsReply proto.InternalMessageInfo

func (m *SearchCarsReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SearchCarsReply) GetCarId() string {
	if m != nil {
		return m.CarId
	}
	return ""
}

type UseCarRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	CarModel             string   `protobuf:"bytes,2,opt,name=CarModel,proto3" json:"CarModel,omitempty"`
	PickupPlace          string   `protobuf:"bytes,3,opt,name=PickupPlace,proto3" json:"PickupPlace,omitempty"`
	DropPlace            string   `protobuf:"bytes,4,opt,name=DropPlace,proto3" json:"DropPlace,omitempty"`
	StartDate            string   `protobuf:"bytes,5,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,6,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseCarRequest) Reset()         { *m = UseCarRequest{} }
func (m *UseCarRequest) String() string { return proto.CompactTextString(m) }
func (*UseCarRequest) ProtoMessage()    {}
func (*UseCarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_sharing_ee7a01c7a2a6d540, []int{4}
}
func (m *UseCarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseCarRequest.Unmarshal(m, b)
}
func (m *UseCarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseCarRequest.Marshal(b, m, deterministic)
}
func (dst *UseCarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseCarRequest.Merge(dst, src)
}
func (m *UseCarRequest) XXX_Size() int {
	return xxx_messageInfo_UseCarRequest.Size(m)
}
func (m *UseCarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UseCarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UseCarRequest proto.InternalMessageInfo

func (m *UseCarRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UseCarRequest) GetCarModel() string {
	if m != nil {
		return m.CarModel
	}
	return ""
}

func (m *UseCarRequest) GetPickupPlace() string {
	if m != nil {
		return m.PickupPlace
	}
	return ""
}

func (m *UseCarRequest) GetDropPlace() string {
	if m != nil {
		return m.DropPlace
	}
	return ""
}

func (m *UseCarRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *UseCarRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type UseCarReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseCarReply) Reset()         { *m = UseCarReply{} }
func (m *UseCarReply) String() string { return proto.CompactTextString(m) }
func (*UseCarReply) ProtoMessage()    {}
func (*UseCarReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_sharing_ee7a01c7a2a6d540, []int{5}
}
func (m *UseCarReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseCarReply.Unmarshal(m, b)
}
func (m *UseCarReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseCarReply.Marshal(b, m, deterministic)
}
func (dst *UseCarReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseCarReply.Merge(dst, src)
}
func (m *UseCarReply) XXX_Size() int {
	return xxx_messageInfo_UseCarReply.Size(m)
}
func (m *UseCarReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UseCarReply.DiscardUnknown(m)
}

var xxx_messageInfo_UseCarReply proto.InternalMessageInfo

func (m *UseCarReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReturnCarRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	CarId                string   `protobuf:"bytes,2,opt,name=CarId,proto3" json:"CarId,omitempty"`
	ReturnDate           string   `protobuf:"bytes,3,opt,name=ReturnDate,proto3" json:"ReturnDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnCarRequest) Reset()         { *m = ReturnCarRequest{} }
func (m *ReturnCarRequest) String() string { return proto.CompactTextString(m) }
func (*ReturnCarRequest) ProtoMessage()    {}
func (*ReturnCarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_sharing_ee7a01c7a2a6d540, []int{6}
}
func (m *ReturnCarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnCarRequest.Unmarshal(m, b)
}
func (m *ReturnCarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnCarRequest.Marshal(b, m, deterministic)
}
func (dst *ReturnCarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnCarRequest.Merge(dst, src)
}
func (m *ReturnCarRequest) XXX_Size() int {
	return xxx_messageInfo_ReturnCarRequest.Size(m)
}
func (m *ReturnCarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnCarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnCarRequest proto.InternalMessageInfo

func (m *ReturnCarRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ReturnCarRequest) GetCarId() string {
	if m != nil {
		return m.CarId
	}
	return ""
}

func (m *ReturnCarRequest) GetReturnDate() string {
	if m != nil {
		return m.ReturnDate
	}
	return ""
}

type ReturnCarReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnCarReply) Reset()         { *m = ReturnCarReply{} }
func (m *ReturnCarReply) String() string { return proto.CompactTextString(m) }
func (*ReturnCarReply) ProtoMessage()    {}
func (*ReturnCarReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_sharing_ee7a01c7a2a6d540, []int{7}
}
func (m *ReturnCarReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnCarReply.Unmarshal(m, b)
}
func (m *ReturnCarReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnCarReply.Marshal(b, m, deterministic)
}
func (dst *ReturnCarReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnCarReply.Merge(dst, src)
}
func (m *ReturnCarReply) XXX_Size() int {
	return xxx_messageInfo_ReturnCarReply.Size(m)
}
func (m *ReturnCarReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnCarReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnCarReply proto.InternalMessageInfo

func (m *ReturnCarReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterCarRequest)(nil), "CarSharing.RegisterCarRequest")
	proto.RegisterType((*RegisterCarReply)(nil), "CarSharing.RegisterCarReply")
	proto.RegisterType((*SearchCarsRequest)(nil), "CarSharing.SearchCarsRequest")
	proto.RegisterType((*SearchCarsReply)(nil), "CarSharing.SearchCarsReply")
	proto.RegisterType((*UseCarRequest)(nil), "CarSharing.UseCarRequest")
	proto.RegisterType((*UseCarReply)(nil), "CarSharing.UseCarReply")
	proto.RegisterType((*ReturnCarRequest)(nil), "CarSharing.ReturnCarRequest")
	proto.RegisterType((*ReturnCarReply)(nil), "CarSharing.ReturnCarReply")
}

func init() { proto.RegisterFile("car_sharing.proto", fileDescriptor_car_sharing_ee7a01c7a2a6d540) }

var fileDescriptor_car_sharing_ee7a01c7a2a6d540 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x6e, 0x9b, 0x30,
	0x14, 0xc6, 0x47, 0xb6, 0xb0, 0xe4, 0x44, 0x5b, 0x16, 0x6b, 0xda, 0x18, 0xcb, 0xa2, 0x08, 0x6d,
	0x52, 0xae, 0xb8, 0xd8, 0xae, 0x76, 0xb3, 0x4d, 0x21, 0x53, 0xd5, 0x4a, 0x69, 0x51, 0x50, 0xae,
	0x2b, 0x07, 0xac, 0x04, 0x85, 0x00, 0xb5, 0x4d, 0xab, 0x3c, 0x4a, 0xa5, 0x3e, 0x44, 0xdf, 0xa0,
	0xaf, 0x56, 0x81, 0x09, 0x98, 0xe6, 0x8f, 0xda, 0x5e, 0xf4, 0x8e, 0x73, 0x3e, 0x7c, 0xfc, 0xfd,
	0x8e, 0x8f, 0x0d, 0x1d, 0x17, 0xd3, 0x73, 0xb6, 0xc0, 0xd4, 0x0f, 0xe7, 0x66, 0x4c, 0x23, 0x1e,
	0x21, 0xb0, 0x30, 0x75, 0x44, 0xc6, 0xb8, 0x51, 0x00, 0x4d, 0xc8, 0xdc, 0x67, 0x9c, 0x50, 0x0b,
	0xd3, 0x09, 0xb9, 0x48, 0x08, 0xe3, 0xa8, 0x0b, 0xcd, 0xb3, 0xab, 0x90, 0xd0, 0x53, 0xbc, 0x22,
	0x9a, 0xd2, 0x57, 0x06, 0xcd, 0x49, 0x99, 0x40, 0x3a, 0x34, 0x2c, 0x4c, 0xc7, 0x91, 0x47, 0x02,
	0xad, 0x96, 0x89, 0x45, 0x8c, 0x3e, 0x42, 0xdd, 0x0e, 0xb0, 0x4b, 0xb4, 0xd7, 0x99, 0x20, 0x82,
	0xb4, 0x9e, 0xc3, 0x31, 0xe5, 0x23, 0xcc, 0x89, 0xf6, 0x46, 0xd4, 0x2b, 0x12, 0x48, 0x83, 0xb7,
	0xff, 0x43, 0x2f, 0xd3, 0xea, 0x99, 0xb6, 0x09, 0x8d, 0x7f, 0xf0, 0xa1, 0xe2, 0x2e, 0x0e, 0xd6,
	0xe8, 0x13, 0xa8, 0x0e, 0xc7, 0x3c, 0x61, 0xb9, 0xb1, 0x3c, 0x4a, 0x77, 0xb6, 0x30, 0x3d, 0xf6,
	0x72, 0x4b, 0x22, 0x30, 0xae, 0x15, 0xe8, 0x38, 0x04, 0x53, 0x77, 0x61, 0x61, 0xca, 0x36, 0x7c,
	0x3a, 0x34, 0xa6, 0xac, 0x82, 0x57, 0xc4, 0x2f, 0x48, 0xf7, 0x17, 0xda, 0xb2, 0xb5, 0xa7, 0xc3,
	0xdd, 0x29, 0xf0, 0x6e, 0xca, 0x88, 0x74, 0x70, 0xcf, 0x05, 0xeb, 0x43, 0xcb, 0xf6, 0xdd, 0x65,
	0x12, 0xcb, 0x78, 0x72, 0x2a, 0x85, 0x1c, 0xd1, 0x28, 0xd7, 0x73, 0xc8, 0x22, 0x51, 0x6d, 0x41,
	0xfd, 0x40, 0x0b, 0xd4, 0x6a, 0x0b, 0x7e, 0x40, 0x6b, 0x03, 0x70, 0x00, 0xdf, 0xf0, 0xd2, 0x39,
	0xe0, 0x09, 0x0d, 0x1f, 0x89, 0xba, 0xb3, 0x5d, 0xa8, 0x07, 0x20, 0xaa, 0x64, 0x4e, 0x04, 0xa3,
	0x94, 0x31, 0x06, 0xf0, 0x5e, 0xda, 0xe5, 0x80, 0x9f, 0x9f, 0xb7, 0x35, 0x90, 0x6e, 0x11, 0x1a,
	0x43, 0x4b, 0x1a, 0x53, 0xd4, 0x33, 0x4b, 0xcd, 0xdc, 0xbe, 0x5d, 0x7a, 0x77, 0xaf, 0x1e, 0x07,
	0x6b, 0xe3, 0x15, 0x3a, 0x01, 0x28, 0xe7, 0x02, 0x7d, 0x93, 0xff, 0xde, 0x1a, 0x65, 0xfd, 0xeb,
	0x3e, 0x59, 0xd4, 0xfa, 0x03, 0xaa, 0x68, 0x30, 0xfa, 0x22, 0xff, 0x58, 0x99, 0x1a, 0xfd, 0xf3,
	0x2e, 0x49, 0xac, 0x3f, 0x82, 0x66, 0xd1, 0x13, 0xf4, 0xc0, 0x78, 0xf5, 0x40, 0x74, 0x7d, 0x8f,
	0x9a, 0x15, 0x1a, 0xfe, 0x86, 0xef, 0x6e, 0xb4, 0x32, 0xe7, 0x3e, 0x5f, 0x24, 0x33, 0x73, 0x86,
	0xdd, 0x25, 0x09, 0x3d, 0x46, 0xe8, 0xa5, 0xef, 0x12, 0x69, 0xe1, 0xb0, 0x5d, 0x7e, 0xdb, 0xe9,
	0x73, 0x65, 0x2b, 0x33, 0x35, 0x7b, 0xb7, 0x7e, 0xdd, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x21,
	0xd2, 0x04, 0xcc, 0x04, 0x00, 0x00,
}
